kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: hello@thenativeweb.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cert-manager-acme
    solvers:
    - http01:
        ingress:
          class: nginx
