kind: Deployment
apiVersion: apps/v1
metadata:
  name: motd-deployment
  namespace: goloroden
spec:
  selector:
    matchLabels:
      application: motd
  template:
    metadata:
      labels:
        application: motd
    spec:
      containers:
      - name: motd-container
        image: goloroden/motd
        ports:
        - name: http
          containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: motd-service
  namespace: goloroden
spec:
  type: NodePort
  selector:
    application: motd
  ports:
  - name: http
    port: 80
    targetPort: http
